SRCDIR := cmath


# Not to be modified

CC := g++
DEBUG := -g
STD := -std=gnu++11

SRC := $(wildcard $(SRCDIR)/*.cpp)

PROJ_ROOT := /home/philip/Desktop/c++/programming_principles

INCS := 
LIBS := -lm

all:
	$(CC) $(DEBUG) $(STD) $(SRC) $(INCS) $(LIBS)
