SRCDIR := ch8/exercise1


# Not to be modified

CC := g++
DEBUG := -g
STD := -std=gnu++11

SRC := $(wildcard $(SRCDIR)/*.cpp)

PROJ_ROOT := /home/philip/Desktop/c++/programming_principles
INC_ROOT := -I$(PROJ_ROOT)/programs/include

all:
	$(CC) $(DEBUG) $(STD) $(SRC) $(INC_ROOT)
