SRCDIR := ch8/exercise1


# Not to be modified

CC := g++
DEBUG := -g
STD := -std=gnu++11

SRC := $(wildcard $(SRCDIR)/*.cpp)
INC_ROOT := -I/home/philip/Desktop/c++/programming_principles/programs/

all:
	$(CC) $(DEBUG) $(STD) $(SRC) $(INC_ROOT)
